# Generated by Django 4.2.4 on 2023-08-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardsecuritysystem", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childparents",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
