# Generated by Django 4.2.4 on 2023-08-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardsecuritysystem", "0003_alter_childparents_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childparents",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="parentsImage/"),
        ),
    ]
