# Generated by Django 4.2.4 on 2023-08-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardsecuritysystem", "0004_alter_childparents_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childparents",
            name="places_of_work",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
