# Generated by Django 4.2.4 on 2023-08-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardsecuritysystem", "0005_alter_childparents_places_of_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="childparents",
            name="parent_qr",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
