# Generated by Django 4.2.4 on 2023-08-25 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cardsecuritysystem", "0007_alter_childparents_parent_qr"),
    ]

    operations = [
        migrations.RenameField(
            model_name="childparents",
            old_name="parent_qr",
            new_name="parentqr",
        ),
    ]
