# Generated by Django 4.2.4 on 2023-08-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardsecuritysystem", "0009_alter_childparents_parentqr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pupil",
            name="Bar_Code",
            field=models.ImageField(null=True, upload_to="userBar"),
        ),
        migrations.AlterField(
            model_name="pupil",
            name="QR_Code",
            field=models.ImageField(null=True, upload_to="userQR/"),
        ),
        migrations.AlterField(
            model_name="pupil",
            name="avatar",
            field=models.ImageField(null=True, upload_to="userprofile/"),
        ),
    ]
