# Generated by Django 4.2.4 on 2023-08-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cardsecuritysystem",
            "0010_alter_pupil_bar_code_alter_pupil_qr_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pupil",
            name="student_class",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pupil",
            name="Bar_Code",
            field=models.ImageField(blank=True, null=True, upload_to="userBar"),
        ),
        migrations.AlterField(
            model_name="pupil",
            name="QR_Code",
            field=models.ImageField(blank=True, null=True, upload_to="userQR/"),
        ),
        migrations.AlterField(
            model_name="pupil",
            name="age",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pupil",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="userprofile/"),
        ),
        migrations.AlterField(
            model_name="pupil",
            name="first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pupil",
            name="last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pupil",
            name="middle_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pupil",
            name="registration_number",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
