# Generated by Django 4.2.4 on 2023-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cardsecuritysystem",
            "0011_pupil_student_class_alter_pupil_bar_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="childparents",
            name="picker",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
