# Generated by Django 4.2.4 on 2023-08-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardsecuritysystem", "0012_childparents_picker"),
    ]

    operations = [
        migrations.AddField(
            model_name="childparents",
            name="picker_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="childparents",
            name="picker_security_question",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
