# Generated by Django 4.2.4 on 2023-08-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardsecuritysystem", "0013_childparents_picker_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="childparents",
            name="picker_security_answer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="childparents",
            name="picker_security_question",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
