# Generated by Django 4.2.4 on 2023-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardsecuritysystem", "0014_childparents_picker_security_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childparents",
            name="parentqr",
            field=models.ImageField(blank=True, null=True, upload_to="parentsQR/"),
        ),
    ]
