# Generated by Django 4.2.4 on 2023-08-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardsecuritysystem", "0015_alter_childparents_parentqr"),
    ]

    operations = [
        migrations.AddField(
            model_name="pupil",
            name="part_payment",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pupil",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="pupil",
            name="school_fee",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pupil",
            name="skin_color",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
