# Generated by Django 4.2.4 on 2023-08-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardsecuritysystem", "0017_pupil_teachers_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="childparents",
            name="picker_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
